//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flee.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Flee.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If(&quot;A&quot; = &quot;A&quot;,
        ///            (
        ///				If((&quot;LongTextToPushScriptLengthOver256CharactersJustToMakeSureItDoesntMatter&quot;) = &quot;C&quot;,
        ///					(
        ///						If((&quot;D&quot;) = &quot;E&quot;,
        ///							2,
        ///							3
        ///						)
        ///					),
        ///					(
        ///						If((&quot;D&quot;) = &quot;E&quot;,
        ///							Ceiling((((((4000) / 46.228) + 8) * 46.228) * 3) + 5126) + 1471 / 304.8 + 20,
        ///							Ceiling(((((((((4000) / 46.228) + 8) * 46.228) * 3) + 5126) + 1217) / 304.8) + 20)
        ///						)
        ///					)
        ///				)
        ///    ),0
        ///  ).
        /// </summary>
        internal static string FailingLongScriptWithManyFunctions {
            get {
                return ResourceManager.GetString("FailingLongScriptWithManyFunctions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If((&quot;LongTextToPushScriptLengthOver256CharactersJustToMakeSureItDoesntMatter&quot;)=&quot;C&quot;, 
        ///    (
        ///    If((&quot;D&quot;)=&quot;E&quot;,
        ///			2, 
        ///			3
        ///        )
        ///    ),
        ///    (
        ///    If((&quot;D&quot;)=&quot;E&quot;,
        ///			Ceiling((( (((4000)/46.228)+8 )*46.228)*3)+5126)+1471/304.8+20, 
        ///			Ceiling(((((( (((4000)/46.228)+8 )*46.228)*3)+5126)+1217)/304.8)+20)
        ///        )
        ///    )
        ///)
        ///.
        /// </summary>
        internal static string LongScriptWithManyFunctions {
            get {
                return ResourceManager.GetString("LongScriptWithManyFunctions", resourceCulture);
            }
        }
    }
}
